### ISSUE TITLE
jewler is messy and doesn't allow for many things, remove it

### ISSUE THREAD

**Issue by krainboltgreene** [anthonator/skittles#11]
Jewler blows for a lot of reasons, but mostly because it dumps a whole lot of junk in your gem when it's really easy to make your own spec.

I suggest removing it, the stuff it generated, and making having a hand made one.

**Comment by anthonator** [comment]
Yeah, I used Jeweler back when I first created the gem a couple years ago. I'll ditch Jeweler in v2.

**Comment by krainboltgreene** [comment]
I'll start working on a PR.

On Wed, May 15, 2013 at 1:17 PM, Anthony Smith notifications@github.comwrote:

> Yeah, I used Jeweler back when I first created the gem a couple years ago.
> I'll ditch Jeweler in v2.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/anthonator/skittles/issues/11#issuecomment-17963442
> .

## 

Kurtis Rainbolt-Greene, Hacker
Software Developer
612 S. Flower St.
Los Angeles, CA, 90017

**Comment by krainboltgreene** [comment]
(Spoiler: I didn't)
