### ISSUE TITLE
Skittles::Error should contain rate limit time wait

### ISSUE THREAD

**Issue by krainboltgreene** [anthonator/skittles#12]
This would allow developers to retry explicitly when Foursquare allows them to retry.

See: twitter gem

**Comment by anthonator** [comment]
Good idea. Does Foursquare have a status code specific to rate limit errors?

**Comment by krainboltgreene** [comment]
The rate limit is apparently listed in the response header. X-RATE-LIMIT or
something. link to docs later.

On Wed, May 15, 2013 at 1:16 PM, Anthony Smith notifications@github.comwrote:

> Good idea. Does Foursquare have a status code specific to rate limit
> errors?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/anthonator/skittles/issues/12#issuecomment-17963384
> .

## 

Kurtis Rainbolt-Greene, Hacker
Software Developer
612 S. Flower St.
Los Angeles, CA, 90017

**Comment by anthonator** [comment]
Rate limit comes back as 403 with an errorType of rate_limit_exceeded.

**Comment by anthonator** [comment]
https://developer.foursquare.com/overview/responses

**Comment by krainboltgreene** [comment]
Here's the details on how they show the rate limit time wait:
https://developer.foursquare.com/overview/ratelimits

On Wed, May 15, 2013 at 1:27 PM, Anthony Smith notifications@github.comwrote:

> https://developer.foursquare.com/overview/responses
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/anthonator/skittles/issues/12#issuecomment-17963984
> .

## 

Kurtis Rainbolt-Greene, Hacker
Software Developer
612 S. Flower St.
Los Angeles, CA, 90017
