### ISSUE TITLE
Loosening up the dependencies a bit?

### ISSUE THREAD

**Issue by asanghi** [anthonator/skittles#6]
I was wondering if you can consider loosening up the dependencies on the gem a bit?

oauth2 is locked to 0.5.x and mime-types is locked to 1.17.x 

Both gems are now bumped up.

It become harder to keep up to date on larger projects because of many dependencies. Please consider?

**Comment by anthonator** [comment]
I updated the dependencies. I haven't pushed a gem yet but you should just be able to grab the source.
